project_name: steam-account-switcher

before:
  hooks:
    - go mod download
    - cp accounts-sample.toml accounts.toml

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - 386
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
      - -H=windowsgui

archives:
  - replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - accounts.toml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
