name: push

on: [push]

jobs:

  build:
    name: Build
    runs-on:  windows-latest
    steps:

      - name: goreleaser
        uses: docker://goreleaser/goreleaser
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          args: release
